### ISSUE TITLE
Front-end templates have invalid content before the doctype

### ISSUE THREAD

**Issue by fordie** [hmrc/init-service#17]
There are 36 mostly blank lines being generated before the doctype declaration includng 3 ')' so ))) is getting rendered before the header in the browser.
![untitled](https://cloud.githubusercontent.com/assets/494985/20181392/eda96334-a755-11e6-9aeb-1cc8e4bf6721.jpeg)

**Comment by feedmypixel** [comment]
There are some extra brackets here https://github.com/hmrc/init-service/blob/master/templates/service/app/views/helloworld/hello_world.scala.html#L1

FYI - @franekrichardson

**Comment by feedmypixel** [comment]
fixed by https://github.com/hmrc/init-service/pull/18
