### ISSUE TITLE
Hardcoded assets-frontend version is out of date

### ISSUE THREAD

**Issue by rpowis** [hmrc/init-service#26]
The version of assets-frontend that's hard coded [here](https://github.com/hmrc/init-service/blob/master/templates/service/conf/application.conf#L71) is out of date.

Rather than it being hard coded and having to update it in the service every time one's been created, could it be made dynamic? it could pull the latest version from somewhere at run time.

**Comment by beny23** [comment]
Closing as no longer applicable
