### ISSUE TITLE
Default Header link to http://www.google.com is inappropriate 

### ISSUE THREAD

**Issue by gordonmcmullan** [hmrc/init-service#31]
The following code supplied a default Nav link which sends users to http://www.google.co.uk/ https://github.com/hmrc/init-service/blob/master/templates/service/app/views/govuk_wrapper.scala.html#L23-L26

We shouldn't supply an off platform Default Home link as there's a risk this might get left in place rather than overridden as intended.

@gavinwye believes that it shouldn't supply any markup by default.

**Comment by beny23** [comment]
Closing as no longer applicable
