### ISSUE TITLE
Generate Test Scaffolding?

### ISSUE THREAD

**Issue by MarkPaxton** [hmrc/init-service#5]
Just a quick question/suggestion on this - is it/can we make it so that it also scaffolds tests for the generated code? It would be fantastically useful to have some template tests as well as the controller, etc.

**Comment by charleskubicek** [comment]
@MarkPaxton what tests were you thinking of? Unit tests? That sounds useful.

**Comment by MarkPaxton** [comment]
Yes, a unit test to demonstrate that hello world is returned from the controller would be nice - just a starting point to expand from as per the controller code.

**Comment by MarkPaxton** [comment]
As it turns out I think it's already there I just missed it somehow!
