### ISSUE TITLE
Enhance MicroserviceController scaffolding

### ISSUE THREAD

**Issue by MarkPaxton** [hmrc/init-service#6]
Just a few suggestions to improve the scaffolding when you create a new service.

When you generate your new microservice using the script it the controller generates is called "MicroserviceHelloWorld". It might be good to use name conventions, e.g. "HelloWorldController" or "${ProjectName}HelloWorldController".

Scaffolding the folder structure (assets, controllers,connectors, services) might also be useful.

Within the controller there is also only 1 method to answer a "get" with hello world. Perhaps expanding this to have scaffolding for all the RESTful api calls would be nice as well.

Finally, is there a way to scaffold an authenticated controller vs a public controller, so that when starting out the auth requirements are baked in with specified Enrollments?

**Comment by beny23** [comment]
Closing as no longer applicable
