### ISSUE TITLE
sbt idea generates out of date project config / import from sbt fails

### ISSUE THREAD

**Issue by MarkPaxton** [hmrc/init-service#7]
When using sbt idea and then opening the project in Idea 2016.1.3 error messages are as shown. Given sbt support in Idea now, should this be removed?

When importing the sbt project within idea it does work ok after configuring the scala sdk to be used in with the project then rebuilding and restarting - otherwise it was not recognizing play libraries, which I suppose is configuration my end since the project files remain unchanged.

![error](https://cloud.githubusercontent.com/assets/275315/16411682/269ca7be-3d20-11e6-9ae9-8b26ee6f281e.png)
![error2](https://cloud.githubusercontent.com/assets/275315/16411683/26a1d13a-3d20-11e6-93f3-362f3dc1cfaf.png)

**Comment by RawToast** [comment]
If you're using IntelliJ 13+, then I would advise not use gen idea and simply import the SBT project. 

The sbt-idea plugin hasn't been updated in over 2 years and the project setup it creates is in an old format, hence IntelliJ giving you that warning. The recommended way to import a play project is via IntelliJ's built-in SBT support, see:

https://www.playframework.com/documentation/2.3.x/IDE#IntelliJ

**Comment by beny23** [comment]
Closing as no longer applicable
